name = "Konkrete [Forge]"
filename = "konkrete_forge_1.3.3_MC_1.18-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3593/196/konkrete_forge_1.3.3_MC_1.18-1.18.1.jar"
hash-format = "sha1"
hash = "efd92532cc154c98ba169fd5f2a45ed683f16334"

[update]
[update.curseforge]
file-id = 3593196
project-id = 410295
